[package]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
copyright = "OCamlPro SAS & Origin Labs SAS"
edition = "4.10.0"
github-organization = "ocamlpro"
kind = "program"
license = "LGPL2"
min-edition = "4.10.0"
name = "ez-cmdliner"
synopsis = "Easy version of Cmdliner"
version = "0.1.0"

# keys that you could also define:
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# documentation = "...documentation..."
# homepage = "...homepage..."

[package]
description = """
ez-cmdliner is a simple layer on top of Cmdliner to provide an interface
à la Arg.parse with an extension for simple sub-commands.
"""

[drom]
skip = "src/main.ml"

[dependencies]

[tools]
dune = "2.6.0"
